### ISSUE TITLE
Verifying?

### ISSUE THREAD

**Issue by baver11** [rev22/curve255js#1]
Is it possible to verify with this library also? 

something like verify(signature, message, publicKey);

**Comment by rev22** [comment]
That isn't implemented by this library.

I suppose you are looking for a public-key signature system based on the same elliptic curve, for example [Ed25519](http://ed25519.cr.yp.to/index.html)

The code for implementing such a system would be quite larger so it would go beyond the scope of this project, however I'll definitely add a link to a good Javascript implementation, if/when it exists. ☺
